services:
  postgres:
    image: postgres:16-alpine
    container_name: retrovault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: retrovault
      POSTGRES_PASSWORD: retrovault
      POSTGRES_DB: retrovault_db
    ports:
      - "4404:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: