services:
  postgres:
    image: postgres:18
    container_name: retrovault-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: retrovault
      POSTGRES_PASSWORD: retrovault
      POSTGRES_DB: retrovault_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: